/'

    Class diagram for Patient Assist Project - SYSDAT F25 

    Crow's Foot Notation:
        Type 	        Symbol
        
        Zero or One 	|o--
        Exactly One 	||--
        Zero or Many 	}o--
        One or Many 	}|--

'/

@startuml
!theme cerulean
skinparam linetype ortho

class App {
    +fontSize
    +screenReader
    +colorContrast
    +accessibilitySettings
    +voiceControl
    +confirmationMessage
    +defaultSettings
    +games
    +changeFontSize()
    +enableScreedReader()
}

class Patient {
    +bedNumber
    +allergies
    +notify()
    +addAppointment()
}

class Menu {
    +dishes
    +addDish()
    +removeDish()
}

class Dish {
    +timeInterval
    +allergens
}

class DishOrder {
    +dish
    +orderStatus
    +deliveryDelay
}

class Allergy {
    +Allergens
}

class Allergen {
    +id
    +name
}

class Game {
    +category
    +difficulty
}

class GameMenu {
}

class Game {
    +difficulty
    +category
    +play()
    +saveScore
}

class KitchenStaff {
}

class Notification {
    +patientId
    +message
}

class Calender {
    +events
    +appointments
    +checkNotifications()
}

class Event {
    +time
    +patients
    +reschedule()
    +cancel()
}

class Appointment {
    +patient
    +employees
}

class Employee {
    +role
    +department
}

class Room {
    +id
    +beds
    +addBed()
    +removeBed()
}

class Bed {
    +id
    +patient
    +addPatient()
    +removePatient()
}

enum Role

/' 

    RELATIONS
    
'/

App --* "1" GameMenu : has
App --* "0..*" Game : has
App --* "1" Calendar : has
Patient --* "1" Calendar : has
Patient "0..*" *--* "0..*" Allergy : has
Allergy "1..*" *--* "0..*" Allergen : has
Dish "1..*" *-- DishOrder : has
Dish --* "0..*" Allergen : has
Calendar --* "0..*" Appointment : has
Calendar --* "0..*" Event : has
Calendar --* "0..*" Notification : has
Event --* "0..*" Patient : has
Appointment --* "1..*" Patient : has
Appointment --* "1..*" Employee : has
Room --* "0..*" Bed : has
Bed --* "0..1" Patient : has
Menu --* "0..1" Dish : has
Employee --* "1..*" Role : has

/' 

    NOTES 
    
'/

@enduml

