/'

    Class diagram for Patient Assist Project - SYSDAT F25 

    Crow's Foot Notation:
        Type 	        Symbol
        
        Zero or One 	|o--
        Exactly One 	||--
        Zero or Many 	}o--
        One or Many 	}|--

'/

@startuml
/'!theme cerulean'/
skinparam linetype ortho

class App {
    +fontSize
    +screenReader
    +colorContrast
    +accessibilitySettings
    +voiceControl
    +confirmationMessage
    +defaultSettings
    +games
    +changeFontSize()
    +enableScreedReader()
}

class Menu {
    +dishes
    +addDish()
    +removeDish()
}

class Dish {
    +timeInterval
    +allergens
}

class DishOrder {
    +dish
    +orderStatus
    +deliveryDelay
}

class Allergy {
    +Allergens
}
note top of Allergy
We do not keep track of patient allergies in the app, 
meaning it is not this system's responsibility 
to filter out food for the patient.
end note

class Allergen {
    +id
    +name
}

class Game {
    +category
    +difficulty
}

class GameMenu {
}

class Game {
    +difficulty
    +category
    +play()
    +saveScore
}

class Notification {
    +message
}

class Calendar {
    +events
    +appointments
    +checkNotifications()
}

class Event {
    +time
    +reschedule()
    +cancel()
    +name
    +description
}

class Employee {
    +role
    +section
}

enum ROLE {
    doctor
    nurse
    chef
    cleaning
}

class Section {
    +id
    +beds
    +addBed()
    +removeBed()
}

class Bed {
    +id
    +patientName
    +addPatient()
    +removePatient()
}
note bottom of Bed
with regards to any information kept about a 
patient; it must not be under GDPR
end note

/' 

    RELATIONS
    
'/

App --* "1" GameMenu : has
App --* "0..*" Game : has
App --* "1" Calendar : has
Allergy --* "1..*" Allergen : has
Dish "1..*" *-- DishOrder : has
Dish --* "0..*" Allergen : has
Calendar --* "0..*" Event : has
Calendar --* "0..*" Notification : has
Section --* "0..*" Bed : has
Menu --* "0..1" Dish : has
Employee --* "1..*" ROLE : has
Employee "0..*" --* "1..*" Section : has

/' 

    NOTES 
    
'/

@enduml

