/'

    Domain model for Patient Assist Project - SYSDAT F25 

    Crow's Foot Notation:
        Type 	        Symbol
        
        Zero or One 	|o--
        Exactly One 	||--
        Zero or Many 	}o--
        One or Many 	}|--

'/

@startuml
!theme superhero
skinparam linetype ortho

entity app {
    +font size
    +screen reader
    +color contrast
    +voice control
}

entity patient {
    +bed number
}

entity order {
    +dish
    +status
    +patient
    +note
}

entity dish {
    +details
    +allergens
    +date
}
note bottom: date: when this dish should be available on a menu

entity kitchen {
    +headchef
}

entity game {
}

entity difficulty {
}

entity category {
}

entity scores {
}

entity headchef {
    +kitchen
}

entity menu {
    +dishes
}

entity calendar {
    +patient
    +appointments
    +events
}

entity appointment {
    +date
}

entity event {
    +date
}

entity doctor {
}

entity nurse {
}

entity training_program {
}

entity exercise {
}

/' 

    RELATIONS
    
'/

patient ||--o{ order
order ||--|{ dish
order }o--|| kitchen

game }o--|| difficulty
game }o--o{ category
game ||--|| scores

kitchen ||--|| menu
kitchen ||--|| headchef

calendar ||--o{ appointment
calendar ||--o{ event
calendar ||--|| patient
calendar }|--o{ order

appointment }o--|| patient
appointment }o--o{ doctor
appointment }o--o{ nurse

patient ||--o{ training_program
training_program ||--o{ exercise

app ||--o{ game

/' 

    NOTES 
    
'/

@enduml
