/'

    EER model for Patient Assist Project - SYSDAT F25 

    Crow's Foot Notation:
        Type 	        Symbol
        
        Zero or One 	|o--
        Exactly One 	||--
        Zero or Many 	}o--
        One or Many 	}|--

'/

@startuml
!theme cyborg
skinparam linetype ortho

entity patient {
    * id : bigint <<PK>>
    --
    * bed number  <<FK>>
}

entity appointment {
    * id : bigint <<PK>>
    --
}

entity room {
    * id : bigint <<PK>>
    --
}
entity bed {
    * id : bigint <<PK>>
    --
}
entity employee {
    * id : bigint <<PK>>
    --
}
entity appointment {
    * id : bigint <<PK>>
    --
}
entity event {
    * id : bigint <<PK>>
    --
}
entity game {
    * id : bigint <<PK>>
    --
}

/' 

    NOTES 
    
'/

@enduml

