/'

    Domain model for Patient Assist Project - SYSDAT F25 

    Crow's Foot Notation:
        Type 	        Symbol
        
        Zero or One 	|o--
        Exactly One 	||--
        Zero or Many 	}o--
        One or Many 	}|--

'/

@startuml
/'!theme cerulean'/
skinparam linetype ortho

entity app {
    +font size
    +screen reader
    +color contrast
    +voice control
}

entity patient {
    +bed number
}

entity bed {
    
}

entity order {
    +dish
    +status
    +bed number
    +note
}

entity dish {
    +details
    +allergens
    +date
}
note bottom: date: when this dish should be available on a menu

entity kitchen {
    +headchef
}

entity game {
    name
    description
}

entity difficulty {
}

entity category {
}

entity scores {
    patient name
    value
}

entity headchef {
    +kitchen
}

entity menu {
    +dishes
}

entity calendar {
    +events
    +meal order time interval
}

entity event {
    date
    name
    description
}

enum ROLE {
    doctor
    nurse
    chef
    cleaning
}

entity staff {
    section
    role
}

entity training_program {
    exercises
    videos
    slides
}

entity exercise {
}

entity section {
    name
    beds
}

/' 

    RELATIONS
    
'/

staff "0..*" -- "1..*" section
bed "0..*" -- "1" section
bed "1" -- "0..*" order
order "0..*" -- "1..*" dish
order "0..*" -- "1" kitchen

game "0..*" -- "1" difficulty
game "0..*" -- "1..*" category
game "1" -- "0..*" scores

kitchen "1" -- "1" menu
kitchen "1" -- "1" headchef

calendar -- "0..*" event
calendar -- "0..*" order

training_program "1..*" -- "1..*" exercise

app -- "0..*" game
app -- "0..*" training_program

staff -- "1..*" ROLE

/' 

    NOTES 
    
'/

@enduml
